### ISSUE TITLE
PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty

### ISSUE THREAD

**Issue by jtorresfabra** [cedricpinson/osgjs#361]
I'm getting this error in Linux with models without normals. Attribute 0 is binded to Normal. Reordering the Program._attributesCache to have Vertex first didn't work for me as the location of the Buffer is decided by using gl.getVertexAttribLocation. See:
https://github.com/cedricpinson/osgjs/blob/develop/sources/osg/Program.js#L231

Maybe I missed something...

**Comment by Kuranes** [comment]
Temp Fix until we find how to force Vertex Attrib Location https://github.com/cedricpinson/osgjs/commit/1b9e7af37ca80ed2b7fdff7cf279a495a0dd656e

As pointed by @jtorresfabra doc from https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices:

"Always have vertex attrib 0 array enabled. If you draw with vertex attrib 0 array disabled, you will force the browser to do complicated emulation when running on desktop OpenGL (e.g. on Mac OSX). This is because in desktop OpenGL, nothing gets drawn if vertex attrib 0 is not array-enabled. You can use bindAttribLocation() to force a vertex attribute to use location 0, and use enableVertexAttribArray() to make it array-enabled."

So that would be the way to do it, but not a simple fix, the Geometry::drawArray and State::lazyDisableVertex are complex beasts of interdepencies along with Program::_cachedAttributes

**Comment by cedricpinson** [comment]
@jtorresfabra could you test, if it works as expected let's merge it

**Comment by jtorresfabra** [comment]
@cedricpinson @Kuranes thumbs up, it fixes the warning. Thanks!

**Comment by Kuranes** [comment]
Definitely fixed by #fc6c385e5abc139a4eee94bef81a59fb28537160
with explicit sorting odf attributes in shader compiler https://github.com/cedricpinson/osgjs/commit/fc6c385e5abc139a4eee94bef81a59fb28537160#diff-b88b11738b3c5573469532874321f000R1021
