### ISSUE TITLE
What provisions does OSGjs have to fit in with OSG via a REST API ?

### ISSUE THREAD

**Issue by AaronNGray** [cedricpinson/osgjs#607]
I am interested in a an application that requires multi user realtime updating access to spatio visual data in a centeralized database for access by OSGjs via a HTTP REST like interface

I posted an issue on OpenSceneGraph GitHub issues wondering whether OpenSceneGraph can be used as a REST server over the web for OSGjs.org for the OSGjs project ? Or whether there is a better route for supporting OSGjs over the web from a cloud based or centralized database ?

I am looking at OSG for experienced users for data entry and scene creation and OSGjs for wider target usage with read only access initially, hopefully leading to data entry, manipulation, and full modification of databases on roll out of the application on the web.

**Comment by jtorresfabra** [comment]
Hi @AaronNGray, 

OpenSceneGraph cannot be used as a REST server, because it is not a server at all. It is a graphics library implementing a scene graph. 

OSG.js is the port of this library to webGL, so it does not provide a server.

In my company we have developed several osgjs applications, and also developed our own servers for each application depending on the needs. (For example http://www.pointcloudviz.com, the server part is done in D language, but we've also developed some servers in dotnet)

So the library does not provide the server part, as it is out of its scope -render things-. You need to implement it yourself, or use third party stuff. 

Hope it helps.

**Comment by AaronNGray** [comment]
Okay.

What is the osgjs data format is that supported/genratable by OSG ?

**Comment by jtorresfabra** [comment]
> What is the osgjs data format is that supported/genratable by OSG ?

Yep it is: ttps://github.com/cedricpinson/osgjs/wiki/Convert-model-with-OSG

**Comment by AaronNGray** [comment]
okay thanks you I will have to download and run both OSG and OSGjs and read the documentation, API's and code to get a proper overview. 

I think for my application I would need to put together a base level general purpose server for serving models to both the OS client based OSG and for OSGjs format for a start. Then add the higher level semantics for my application domain and hopefully do this in a general purpose way that is a reusable framework.

Many thanks.
