### ISSUE TITLE
Matrix/Vec data types too rigid.  

### ISSUE THREAD

**Issue by jtorresfabra** [cedricpinson/osgjs#648]
Right now the possibility to choose between 32/64 bits data types when creating Matrix/Vec/Quat is only offered in compile time, modifying the https://github.com/cedricpinson/osgjs/blob/master/sources/config.js file.

The point of this issue is to get a flexible way to let the user to choose the internal data type when creating Matrices/Vecs/Quats. 

In my particular use case I use Matrices to position/scale/transform my objects in a huge space, so I need them to be 64 bits, otherwise I get precission issues. I don't need the vertices to be in 64 bits, and if I do it I'm somehow wasting resources.  That kind of structure is used often in OSG, but right now it is not possible to do that kind of things in osg.js.

Maybe we can have different constructors for different type of data:

Mat4.create / Mat4.createFloat64 / Mat4.createFloat32 and same thing for Vec classes. 

Also is probably a good thing to move to a glMatrix kind of API, maybe using a wrapper on top of it.

Thoughts?

**Comment by cedricpinson** [comment]
Some extra thoughts
- using glMatrix needs to keep backward compatible api to make the switch smooth and be sure everything works as before
- needs to sepcify the type of Matrix/Vec float32/float64 like in osg, could be something like:
Mat4.createFloat32
Mat4.createFloat64

the point is that if we do that it means that Mat4.mult(result, m1, m2) could accept arguments with float32 and float64 array. It's not really a problem unless we use simd intructions internally of Mat4/VecX. It will require same input type.

Also not sure it's really a problem because to get performance improvement from simd you need to organise your data in a very specific way and do the same operation many times. So if one day we use simd it will be probably a specific case.

**Comment by Kuranes** [comment]
perhaps we couldn't post an issue on their repos ?
Perhaps could make sense for other glmatrix users and thus making it to core glmatrix, saving us from maintaining that ?

**Comment by jtorresfabra** [comment]
@Kuranes, @cedricpinson  

FYI https://github.com/toji/gl-matrix/issues/192 . So it seems they delegate the creation to the user, in case the user wants to use 64 bit precision.

**Comment by cedricpinson** [comment]
I added a summary of the current state of what we want to do, keeping discussion here, and current state on this documents. https://github.com/cedricpinson/osgjs/wiki/Change-Matrix-Vector-operation-to-an-C-api-like-glMatrix

**Comment by cedricpinson** [comment]
we now use glMatrix. closing the issue
