### ISSUE TITLE
How to convert osgjs back to obj

### ISSUE THREAD

**Issue by jasonwang01** [cedricpinson/osgjs#650]
Hi I started using osgjs and it is great. However, I found that the conversion from obj to osgjs is not bi-directional. For example, I can use osgconv to do obj->osg.gles->osgjs, but not osgjs->osg or osgjs->obj. The problem is that I can't edit the osgjs files. If I'm using a webapp and the author did not provide the original obj or osg files, I have no way to add my own model or animation. Is there a tool that can port osgjs model or animations back to osg format?

Thank you!

**Comment by cedricpinson** [comment]
It would be good to be able to read back osgjs to osg but in my knowledge nobody worked on this yet.

**Comment by AquilesCanta** [comment]
Hello @cedricpinson, sorry for the spam. Do you know if this has changed? Is there any known tool for converting osgjs to osg? Thanks!

**Comment by cedricpinson** [comment]
nop nothing changed on this

**Comment by Xeddius** [comment]
I find it really annoying that there's no option to convert back, I lost most of my .blend files when my old system drive died, I've managed to recover some of them in osgjs format that I set up for my webpage viewer (because it was on my server) but there's still no way to actually convert the files back to an editable format. Can someone please work on this so I can get back my years of work?
