### ISSUE TITLE
About mymap.earth and kml

### ISSUE THREAD

**Issue by zebrainncu** [cedricpinson/osgjs#883]
Hi
How to Load '.earth' and '.kml' In osgjs?

In c++
int main(int argc, char **argv)
{	
	osg::ref_ptr<osg::Group> root = new osg::Group();
	osg::ref_ptr<osg::Node> node = osgDB::readNodeFile("mymap.earth");
	
	//add earth
	root->addChild(node.get());
	osgUtil::Optimizer optimizer;
	optimizer.optimize(root.get());

	osg::ref_ptr<osgViewer::Viewer> viewer = new osgViewer::Viewer();
	viewer->setSceneData(root.get());
	viewer->realize();
	viewer->run();
	return 0;
}

ref1: mymap.earth as below
![image 9](https://user-images.githubusercontent.com/16786888/31472850-aa9e9cb8-af23-11e7-8565-a16bcdf2cac1.png)

ref2: about world.tif
https://github.com/gwaldron/osgearth/blob/master/data/world.tif

Thanks!

**Comment by cedricpinson** [comment]
We dont have this reader in javascript, but if you need it you could make a PR to create a reader for this. Another way could be to convert this model with osg to osgjs (there is an osgjs writer plugin for osg)

**Comment by jtorresfabra** [comment]
Hi @zebrainncu, 

I think you are referring to osgEarth instead of OSG. osg is not able to read .earth files if you don't compile osgEarth plugin, which is not contained in OSG. 

So I don't think is an easy task to add a loader for this, but definitely you can write your own plugins. 

See:
https://github.com/cedricpinson/osgjs/tree/master/sources/osgPlugins

Also not sure you can convert the database using osgconv, but maybe is worth to have a try. I did myself with success with VirtualPlanetBuilder databases so it might be possible.

Cheers.
