### ISSUE TITLE
How to speedup computeIntersections?

### ISSUE THREAD

**Issue by BjornMelgaard** [cedricpinson/osgjs#905]
This is the chunk of code that draws line on 3d model of map (I'm not author)

```js
StereoInteraction.prototype.onMouseMove = function (ev) {
  const hit = this.rayCast(ev);
  if (hit) this.drawContinue(hit);
};

StereoInteraction.prototype.rayCast = function (ev) {
  const x = ev.pageX - $(ev.target).offset().left;
  const y = ev.pageY - $(ev.target).offset().top;

  const ratioX = this.stereo.canvas.width / this.stereo.canvas.clientWidth;
  const ratioY = this.stereo.canvas.height / this.stereo.canvas.clientHeight;

  const hits = this.stereo.viewer.computeIntersections(x * ratioX, (this.stereo.canvas.clientHeight - y) * ratioY);

  hits.sort((a, b) => a.ratio - b.ratio);

  if (hits.length !== 1) return null;
  const point = hits[0].point;

  const worldPoint = osg.Vec3.create();
  this.reserveMatrixStack.reset();
  StereoUtils.transformMat4(worldPoint, point, osg.computeLocalToWorld(hits[0].nodepath.slice(0), true, this.reserveMatrixStack.get()));

  return worldPoint;
};
```

The problem is `this.stereo.viewer.computeIntersections` takes enormously much time (0.2 sec) ([on this line](https://github.com/cedricpinson/osgjs/blob/f49c62c7936596ea1c65cbfae5d85af1c1c74e96/sources/osgViewer/View.js#L237)) and I don't know why. Can someone give me a hint?

For example:
- can it be because of big scene?
- what is `traversalMask`?

P.S. api page [is not working](http://osgjs.org/docs/annotated-source/osg.html) (from link [there](http://osgjs.org/index.html#concepts) (`API (auto-generated)`))

**Comment by jtorresfabra** [comment]
Hi @BjornMelgaard, 

Most likely is because your scene is quite big. Best you can do is to build the kdtree for the scene have a look to the picking example specially at https://github.com/cedricpinson/osgjs/blob/master/examples/picking/main.js#L85-L90. 

The traversal mask is used to determine which nodes will be traversed during the update/cull/render phase. In case of intersection it can be used to discard nodes from being intersected. 

Hope it helps.

**Comment by BjornMelgaard** [comment]
Hi @jtorresfabra !!

Thanks for help, it works like magic, I just had to add it after load

Yeeeee :heart: :tada:
